// <auto-generated />
namespace sample.T4M.UI.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DataNula : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataNula));
        
        string IMigrationMetadata.Id
        {
            get { return "201603230109340_Data Nula"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
