// <auto-generated />
namespace sample.T4M.UI.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class LimitedeTeste : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LimitedeTeste));
        
        string IMigrationMetadata.Id
        {
            get { return "201603230050585_Limite de Teste"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
