//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDSoft.APOL.UI.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDSoft.APOL.UI.Tests.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de listagem não encontrada!.
        /// </summary>
        internal static string ERRO_ACESSAR_PAGINA_LISTA_JEIMIS {
            get {
                return ResourceManager.GetString("ERRO_ACESSAR_PAGINA_LISTA_JEIMIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecione um arquivo .jpg (imagem)..
        /// </summary>
        internal static string ERRO_CADASTRO_JEIMIS_ARQUIVO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERRO_CADASTRO_JEIMIS_ARQUIVO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem cadastrada com sucesso!.
        /// </summary>
        internal static string SUCESSO_CADASTRAR_IMAGEM_JEIMIS {
            get {
                return ResourceManager.GetString("SUCESSO_CADASTRAR_IMAGEM_JEIMIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem excluida com sucesso!.
        /// </summary>
        internal static string SUCESSO_EXCLUIR_IMAGEM_JEIMIS {
            get {
                return ResourceManager.GetString("SUCESSO_EXCLUIR_IMAGEM_JEIMIS", resourceCulture);
            }
        }
    }
}
